# Generated by Django 5.0.6 on 2024-05-21 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0042_rename_pedido_preco_pedidos_pedido_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTarefas',
            fields=[
                ('status_tarefa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fechado', models.BooleanField(default=False)),
                ('status_descricao', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarefas',
            fields=[
                ('tipo_tarefa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tarefa_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('tarefa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa_nome', models.CharField(max_length=100, null=True)),
                ('outro_motivo_negocio_perdido', models.CharField(max_length=255, null=True)),
                ('inicio_tarefa', models.DateTimeField(null=True)),
                ('fim_tarefa', models.DateTimeField(null=True)),
                ('registro_tarefa', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('criador_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tarefa', to=settings.AUTH_USER_MODEL)),
                ('pedido_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.pedidos')),
                ('pesquisa_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.pesquisas')),
                ('responsavel_tarefa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.vendedores')),
                ('status_tarefa_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarefas.statustarefas')),
                ('tipo_tarefa_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tipotarefas')),
            ],
        ),
        migrations.CreateModel(
            name='TarefasAtividades',
            fields=[
                ('tarefa_atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('atividade_realizada', models.CharField(max_length=255, null=True)),
                ('registro_atividade', models.DateTimeField(auto_now_add=True, null=True)),
                ('tarefa_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefas')),
                ('usuario_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_atividade', to=settings.AUTH_USER_MODEL)),
                ('tipo_tarefa_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tipotarefas')),
            ],
        ),
    ]
