# Generated by Django 5.0.6 on 2024-05-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='responsavel_tarefa',
            new_name='vendedor_id',
        ),
    ]
