# Generated by Django 5.0.6 on 2024-06-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_responsavel_tarefa_tarefas_vendedor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustarefas',
            old_name='status_descricao',
            new_name='status_nome',
        ),
    ]
