# Generated by Django 5.0.6 on 2024-06-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_status_descricao_statustarefas_status_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='criador_tarefa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tarefa', to=settings.AUTH_USER_MODEL),
        ),
    ]
