# Generated by Django 5.0.6 on 2024-06-07 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_pedido_preco_pedidos_pedido_valor_and_more'),
        ('tarefas', '0005_alter_tarefas_pesquisa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='pedido_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pedidos'),
        ),
    ]
