# Generated by Django 5.0.8 on 2024-08-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasVenda',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoClientes',
            fields=[
                ('classificacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('fornecedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor_nome', models.CharField(max_length=100, null=True)),
                ('contato', models.CharField(max_length=100, null=True)),
                ('aniversario', models.DateTimeField(null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=200, null=True)),
                ('numero_rua', models.CharField(max_length=100, null=True)),
                ('complemento_rua', models.CharField(max_length=100, null=True)),
                ('ponto_referencia', models.CharField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('observacao', models.TextField(max_length=200, null=True)),
                ('fornecedor_lat', models.CharField(max_length=100, null=True)),
                ('fornecedor_lng', models.CharField(max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransportes',
            fields=[
                ('tipo_transporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transporte_nome', models.CharField(max_length=100, null=True)),
                ('cif', models.BooleanField(default=False)),
                ('fob', models.BooleanField(default=False)),
                ('carregamento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('transporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('transporte_nome', models.CharField(max_length=100, null=True)),
                ('capacidade_kg', models.FloatField()),
                ('capacidade_un', models.IntegerField()),
                ('preco_km', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendedor_nome', models.CharField(max_length=100, null=True)),
                ('area_vendedor', models.CharField(max_length=100, null=True)),
                ('comissao_padrao_percentual', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(max_length=100, null=True)),
                ('contato', models.CharField(max_length=100, null=True)),
                ('aniversario', models.DateTimeField(null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=200, null=True)),
                ('numero_rua', models.CharField(max_length=100, null=True)),
                ('complemento_rua', models.CharField(max_length=100, null=True)),
                ('ponto_referencia', models.CharField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('observacao', models.TextField(max_length=200, null=True)),
                ('cliente_lat', models.CharField(default=0, max_length=100, null=True)),
                ('cliente_lng', models.CharField(default=0, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('area_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.areasvenda')),
                ('classificacao_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.classificacaoclientes')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('orcamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('tipo_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes')),
                ('transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes')),
                ('vendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto_nome', models.CharField(max_length=100, null=True)),
                ('peso_produto', models.FloatField()),
                ('embalagem_produto', models.CharField(max_length=100, null=True)),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('item_orcamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('orcamento_quantidade', models.IntegerField(null=True)),
                ('orcamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orcamentos')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('preco_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_compra', models.FloatField()),
                ('preco_sugestao', models.FloatField()),
                ('fornecedor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.fornecedores')),
                ('produto_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisas',
            fields=[
                ('pesquisa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pesquisa_preco', models.FloatField(null=True)),
                ('pesquisa_preco_sugerido', models.FloatField(null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marcas')),
                ('tipo_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes')),
                ('transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_comissao', models.FloatField(null=True)),
                ('pedido_quantidade', models.IntegerField(null=True)),
                ('pedido_data', models.DateTimeField(null=True)),
                ('pedido_condicao_pagamento', models.CharField(max_length=100, null=True)),
                ('pedido_valor', models.FloatField(null=True)),
                ('cliente_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
                ('tipo_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes')),
                ('transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes')),
                ('vendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedores')),
            ],
        ),
    ]
