# Generated by Django 5.0.7 on 2024-07-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nome', models.CharField(max_length=50, null=True)),
                ('estado_sigla', models.CharField(max_length=2, null=True)),
                ('estado_capital', models.CharField(max_length=2, null=True)),
                ('estado_area', models.FloatField(null=True)),
                ('estado_populacao', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('cidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade_nome', models.CharField(max_length=50, null=True)),
                ('cidade_codigo_ibge', models.CharField(max_length=20, null=True)),
                ('cidade_estado', models.CharField(max_length=2, null=True)),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estados')),
            ],
        ),
    ]
