# Generated by Django 5.0.7 on 2024-07-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cidade_clientes_lat_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='lat_cliente',
            new_name='cliente_lat',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='lng_cliente',
            new_name='cliente_lng',
        ),
    ]
