# Generated by Django 5.0.8 on 2024-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pesquisas_fornecedor_id_pesquisas_volume_mensal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('condicao_pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('condicao_pagamento_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
