# Generated by Django 5.0.7 on 2024-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estados_cidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados',
            name='estado_area',
        ),
        migrations.RemoveField(
            model_name='estados',
            name='estado_populacao',
        ),
        migrations.AlterField(
            model_name='estados',
            name='estado_capital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
