# Generated by Django 5.0.7 on 2024-07-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_estados_estado_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cliente_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_long',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_long',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.cidades'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.cidades'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
        ),
    ]
