# Generated by Django 5.0.8 on 2024-08-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_condicaopagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido_condicao_pagamento',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='condicao_pagamento_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.condicaopagamento'),
        ),
    ]
