# Generated by Django 5.0.7 on 2024-07-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_lat_cliente_clientes_cliente_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='cidade',
            new_name='fornecedor_lat',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='estado',
            new_name='fornecedor_lng',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cidade_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.cidades'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='estado_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
        ),
    ]
