# Generated by Django 5.0.7 on 2024-08-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cidade_fornecedores_fornecedor_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cidade_id',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='cidade_id',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='estado_id',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Cidades',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
