# Generated by Django 5.0.7 on 2024-07-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientes_cliente_lat_clientes_cliente_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='cidade',
            new_name='cidade_id',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='estado',
            new_name='estado_id',
        ),
    ]
