# Generated by Django 5.0.7 on 2024-07-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_cidade_fornecedores_cidade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cidades'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
        ),
    ]
