FROM node:alpine

WORKDIR /frontend

# Copy package.json and package-lock.json first to leverage Docker layer caching
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend files
COPY ./frontend .

# Install additional dependencies if needed (they should ideally be part of package.json)
# RUN npm install react-beautiful-dnd react-google-charts serve
# RUN npm install react-beautiful-dnd

# Expose the Vite default port
EXPOSE 5173

# Set the default command to run the dev-exposed script
CMD ["npm", "run", "dev-exposed"]
