# Generated by Django 5.0.4 on 2024-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_aniversario_cliente_cidade_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='complemento_rua',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_rua',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ponto_referencia',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
