# Generated by Django 5.0.4 on 2024-04-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_complemento_rua_cliente_numero_rua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valor_mensal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
