# Generated by Django 5.0.4 on 2024-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cliente_endereco_remove_cliente_valor_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
