# Generated by Django 5.0.4 on 2024-04-17 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cliente_bairro_alter_cliente_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('contato', models.CharField(max_length=100, null=True)),
                ('aniversario', models.DateTimeField(null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=200, null=True)),
                ('numero_rua', models.CharField(max_length=100, null=True)),
                ('complemento_rua', models.CharField(max_length=100, null=True)),
                ('ponto_referencia', models.CharField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('observacao', models.TextField(max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('distancia', models.FloatField()),
                ('comissao_percentual', models.FloatField(blank=True, default=0, null=True)),
                ('custo_transporte_km', models.FloatField()),
                ('custo_transporte_total', models.FloatField()),
                ('preco_inicial', models.FloatField()),
                ('preco_negociado', models.FloatField()),
                ('preco_final', models.FloatField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('peso_produto', models.FloatField()),
                ('embalagem_produto', models.CharField(max_length=100, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransportes',
            fields=[
                ('tipo_transporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transporte', models.CharField(max_length=100, null=True)),
                ('cif', models.BooleanField(default=False)),
                ('fob', models.BooleanField(default=False)),
                ('carregamento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('transporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('transporte', models.CharField(max_length=100, null=True)),
                ('capacidade_kg', models.FloatField()),
                ('capacidade_un', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vendedor', models.CharField(max_length=100, null=True)),
                ('area_vendedor', models.CharField(max_length=100, null=True)),
                ('comissao_padrao_percentual', models.FloatField(default=1.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='transporte_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='vendedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedores'),
        ),
    ]
