# Generated by Django 5.0.4 on 2024-04-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fornecedores_produtos_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='marca_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.marcas'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipo_transporte_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes'),
        ),
    ]
