# Generated by Django 5.0.4 on 2024-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pedidos_marca_id_pedidos_tipo_transporte_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='marca',
            new_name='marca_nome',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='marca',
            new_name='marca_nome',
        ),
    ]
