# Generated by Django 5.0.4 on 2024-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_marca_marcas_marca_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='marca_nome',
            new_name='marca_id',
        ),
    ]
