# Generated by Django 5.0.4 on 2024-04-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_marca_nome_produtos_marca_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nome',
            new_name='cliente_nome',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='marca_id',
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('preco_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_compra', models.FloatField()),
                ('preco_sugestao', models.FloatField()),
                ('fornecedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fornecedores')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
            ],
        ),
    ]
