# Generated by Django 5.0.4 on 2024-04-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_nome_clientes_cliente_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='nome',
            new_name='fornecedor_nome',
        ),
    ]
