# Generated by Django 5.0.4 on 2024-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_nome_fornecedores_fornecedor_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='produto',
            new_name='produto_nome',
        ),
    ]
