# Generated by Django 5.0.4 on 2024-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='teste',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
