# Generated by Django 5.0.4 on 2024-04-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tabela_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='fornecedor_id',
        ),
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='produto_id',
        ),
        migrations.DeleteModel(
            name='Tabela',
        ),
        migrations.DeleteModel(
            name='TabelaPrecos',
        ),
    ]
