# Generated by Django 5.0.4 on 2024-04-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tabelaprecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='fornecedor_id',
        ),
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='produto_id',
        ),
    ]
