# Generated by Django 5.0.4 on 2024-04-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_tabelaprecos_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelaPrecos',
        ),
    ]
