# Generated by Django 5.0.4 on 2024-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_tabelaprecos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('preco_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_compra', models.FloatField()),
                ('preco_sugestao', models.FloatField()),
            ],
        ),
    ]
