# Generated by Django 5.0.4 on 2024-04-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tabelaprecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaprecos',
            name='produto_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.produtos'),
        ),
    ]
