# Generated by Django 5.0.4 on 2024-04-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tabelaprecos_fornecedor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelaPrecos',
        ),
    ]
