# Generated by Django 5.0.4 on 2024-04-26 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_tabelaprecos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('preco_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_compra', models.FloatField()),
                ('preco_sugestao', models.FloatField()),
                ('fornecedor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.fornecedores')),
                ('produto_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
            ],
        ),
    ]
