# Generated by Django 5.0.4 on 2024-04-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_tabelaprecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='produto_id',
        ),
    ]
