# Generated by Django 5.0.4 on 2024-04-26 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_tabelaprecos_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaprecos',
            name='fornecedor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.fornecedores'),
        ),
    ]
