# Generated by Django 5.0.4 on 2024-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_tabelaprecos_fornecedor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipotransportes',
            old_name='tipo_transporte',
            new_name='tipo_transporte_nome',
        ),
        migrations.RenameField(
            model_name='transportes',
            old_name='transporte',
            new_name='transporte_nome',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
