# Generated by Django 5.0.4 on 2024-04-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_tipo_transporte_tipotransportes_tipo_transporte_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedores',
            old_name='nome_vendedor',
            new_name='vendedor_nome',
        ),
    ]
