# Generated by Django 5.0.4 on 2024-04-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_nome_vendedor_vendedores_vendedor_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='quantidade',
            new_name='pedido_quantidade',
        ),
    ]
