# Generated by Django 5.0.4 on 2024-04-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_quantidade_pedidos_pedido_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='comissao_percentual',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='custo_transporte_km',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='custo_transporte_total',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='preco_final',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='preco_inicial',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='preco_negociado',
        ),
    ]
