# Generated by Django 5.0.4 on 2024-04-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_pedidos_comissao_percentual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_transporte_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes'),
        ),
    ]
