# Generated by Django 5.0.4 on 2024-04-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_pedidos_tipo_transporte_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('orcamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('tipo_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes')),
                ('transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes')),
                ('vendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('item_orcamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('orcamento_quantidade', models.IntegerField(null=True)),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
                ('orcamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orcamentos')),
            ],
        ),
    ]
