# Generated by Django 5.0.4 on 2024-04-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_orcamentos_itensorcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisas',
            fields=[
                ('pesquisa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pesquisa_preco', models.FloatField(null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marcas')),
                ('tipo_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransportes')),
                ('transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportes')),
            ],
        ),
    ]
