# Generated by Django 5.0.4 on 2024-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_pesquisas_pesquisa_preco_sugerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasVenda',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoClientes',
            fields=[
                ('classificacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao_nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
