# Generated by Django 5.0.4 on 2024-04-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_areasvenda_classificacaoclientes_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='area_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.areasvenda'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='classificacao_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.classificacaoclientes'),
        ),
    ]
