# Generated by Django 5.0.4 on 2024-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_clientes_area_id_clientes_classificacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportes',
            name='preco_km',
            field=models.FloatField(default=0, null=True),
        ),
    ]
