# Generated by Django 5.0.4 on 2024-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_transportes_preco_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pedido_comissao',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_preco',
            field=models.FloatField(null=True),
        ),
    ]
