# Generated by Django 5.0.4 on 2024-04-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_pedidos_pedido_comissao_pedidos_pedido_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='pedido_preco',
            new_name='pedido_valor',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_condicao_pagamento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
