FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx/nginx-prd.conf /etc/nginx/conf.d/nginx-prd.conf
COPY ./docker/nginx/cert.pem /etc/nginx/cert.pem
COPY ./docker/nginx/key.pem /etc/nginx/key.pem

CMD [ "nginx-debug", "-g", "daemon off;" ]